### ISSUE TITLE
Refreshing of expired certificates

### ISSUE THREAD

**Issue by csware** [philfry/ocsp_proxy#1] opened 2019-03-06 16:41 UTC
There seems to be no logic to remove expired/unused certificates from the cache, and, thus, from the automatic refresh logic. Especially when using Let's Encrypt, where certificates should be replaced after 60 days, the cache will continue to refresh unused certificates forever once a day.

**Comment by csware** [comment] 2019-03-06 16:51
I see two easy options:

* Introduce a "first seen" flag in the cache and stop refreshing after a configurable amount of time (maybe also purge that entry from the cache; here the last accessed date could also be used).
* Provide two hooks scripts, one which can be used before a new certificate is activated (in order to pre-load the cache; `openssl ocsp -issuer intermediate.pem -cert acertificate.pem -url http://127.0.0.1:8888/ -header Host=ocsp.int-x3.letsencrypt.org -no_nonce` does the trick for Let's Encrypt) and one which can be used after a certificate was replaced (in order to purge if from the cache).

**Comment by philfry** [comment] 2019-03-08 09:02
As even (still in use but) expired certificates need a valid ocsp answer to be stacked with if using `ocsp-must-staple` it might be risky to remove expired certificates from cache after a given time: an expiration warning in your browser can be overridden, but you cannot skip an invalid or missing ocsp response (at least not with a few clicks). So websites with expired certificates will, in worst case, become unavailable when both the ocsp responder is down and the cache is empty.
Imho, the only way to purge specific entries from the cache should be to remove them or triggering a removal externally.
Until there's a script for that, please use this snippet to expire certs from the redis cache:
```bash
eval `openssl x509 -in certificate.pem -noout -serial`
eval `openssl x509 -in issuer.pem -noout -ocspid | sed -n 's/ *Public key.*: /ihash=/p'`
redis-cli del ocspxy_${ihash,,}0x${serial,,}
```

After spending a few thoughts on it – how about triggering the expiry from cache by sending a special header, e.g.
```
openssl ocsp \
  -issuer /path/to/issuer.pem \
  -cert /path/to/cert.pem \
  -header X-prune-from-cache=true
```
?

**Comment by philfry** [comment] 2019-03-11 09:35
Should be fixed with 0.4, please take a look. If the solution is not convenient for you, please reopen this issue.

**Closed as completed by philfry** 2019-03-11 09:35 UTC

**Comment by csware** [comment] 2019-03-15 18:15
Thanks!

However, there seems to be a problem with `openssl x509 -in certificate.pem -noout -serial` if the serial number starts with a 0. ocsp_proxy seems to ignore/skip it.

**Comment by philfry** [comment] 2019-03-15 18:41
I have a letsencrypt certificate with a serial that begins with zero, but I'm unable to reproduce your issue:

- warm up the cache

cli:
```
Response verify OK
/tmp/tmp.BFTG6Nrmeh/cert.pem: good
	This Update: Mar 15 13:00:00 2019 GMT
	Next Update: Mar 22 13:00:00 2019 GMT
```
ocsp_proxy:
```
[info] connection from 127.0.0.1:45060
[debug] cache key is ocspxy_a84a6a63047dddbae6d139b7a64565eff3a8eca10xmyserialwithoutleadingzero
[debug] cache needs update
[debug] forwarding ocsp request to ocsp.int-x3.letsencrypt.org
[debug] ocsp responder answered
[debug] got a valid ocsp response: [this:1552654800] [next:1553259600] [status:good]
[debug] sending response
[debug] disconnecting 127.0.0.1:45060
```
- query again

cli:
```
Response verify OK
/tmp/tmp.9J0c1u0DWU/cert.pem: good
	This Update: Mar 15 13:00:00 2019 GMT
	Next Update: Mar 22 13:00:00 2019 GMT
```
ocsp_proxy:
```
[info] connection from 127.0.0.1:45080
[debug] cache key is ocspxy_a84a6a63047dddbae6d139b7a64565eff3a8eca10xmyserialwithoutleadingzero
[debug] sending response
[debug] disconnecting 127.0.0.1:45080
```

**Comment by csware** [comment] 2019-03-15 20:07
It's for purging the cache using cli only.

**Comment by philfry** [comment] 2019-03-15 21:51
purging works fine for me, too:
cli:
```
Error querying OCSP responder
140054767085376:error:27076072:OCSP routines:parse_http_line1:server response error:crypto/ocsp/ocsp_ht.c:260:Code=410,Reason=Gone
```
(this response is correct: the cache entry is "gone")
ocsp_proxy:
```
[info] connection from 127.0.0.1:47314
[debug] cache key is ocspxy_a84a6a63047dddbae6d139b7a64565eff3a8eca10xmyserialwithoutleadingzero
[info] removing ocspxy_a84a6a63047dddbae6d139b7a64565eff3a8eca10xmyserialwithoutleadingzero from cache
[debug] disconnecting 127.0.0.1:47314
```
re-adding the ocsp request again:
```
Response verify OK
/tmp/tmp.l99tnYxJoW/cert.pem: good
	This Update: Mar 15 13:00:00 2019 GMT
	Next Update: Mar 22 13:00:00 2019 GMT
```
```
[info] connection from 127.0.0.1:47352
[debug] cache key is ocspxy_a84a6a63047dddbae6d139b7a64565eff3a8eca10xmyserialwithoutleadingzero
[debug] cache needs update
[debug] forwarding ocsp request to ocsp.int-x3.letsencrypt.org
[debug] ocsp responder answered
[debug] got a valid ocsp response: [this:1552654800] [next:1553259600] [status:good]
[debug] sending response
[debug] disconnecting 127.0.0.1:47352
```

**Comment by csware** [comment] 2019-03-15 21:58
Please don't use the http way for purging, but the second way (of https://github.com/philfry/ocsp_proxy/blob/master/README.md) where you issue `openssl x509 -in certificate.pem -noout -serial` as I quoted in my inital comment (https://github.com/philfry/ocsp_proxy/issues/1#issuecomment-473391866). Then the resulting redis key is `0x03` (maybe this related to OpenSSL 1.1)...

**Comment by philfry** [comment] 2019-03-15 22:21
Ah, now I understand your problem. You're about to delete the key from the redis database directly.
That's right, the simple example won't work with serials with leading zeroes as leading zeroes are usually skipped when interpreted as number (and not as string).
In this case, try something like:
```bash
eval `openssl x509 -in certificate.pem -noout -serial`
serial=${serial##+(0)}
eval `openssl x509 -in issuer.pem -noout -ocspid | sed -n 's/ *Public key.*: /ihash=/p'`
redis-cli del ocspxy_${ihash,,}0x${serial,,}
```
